DELETE http://localhost:3003/api/blogs/68f6485b64f930ae74e6eb58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4ZjVlNjBjMzQzZTQ4YWFhNDBhNjRlZCIsImlhdCI6MTc2MTAzMjU1MX0.UqmPKBRT8ltjZr9vxX_EjhRxou1nRFCVqG97wo5mRaw